services:
  vector_service:
    build:
      context: ./vector_service
    container_name: vector_service
    ports:
      - "8000:8000"
    volumes:
      - ./vector_service:/app
    env_file:
      - .env
    networks:
      - app_network

  chatbot_app:
    build:
      context: ./chatbot_app
    container_name: chatbot_app
    ports:
      - "8517:8517"
    volumes:
      - ./chatbot_app:/app
    env_file:
      - .env
    networks:
      - app_network
    depends_on:
      - vector_service

networks:
  app_network:
    driver: bridge
